const drinks = [
  {
    category: "Traditional",
    name: "House Coffee",
    info: "",
    price: 2,
  },
  {
    category: "Traditional",
    name: "Espresso",
    info: "",
    price: 4,
  },
  {
    category: "Traditional",
    name: "Americano",
    info: "",
    price: 4,
  },
  {
    category: "Traditional",
    name: "Cappuccino",
    info: "",
    price: 5,
  },
  {
    category: "Traditional",
    name: "Latte",
    info: "",
    price: 5.5,
  },
  {
    category: "Traditional",
    name: "Cold Brew",
    info: "",
    price: 5.5,
  },
  {
    category: "House Specials",
    name: "1987 (Iced)",
    info: "Hazelnut iced coffee sweetened with condensed milk, topped with sea salt cream & ibarra chocolate",
    price: 6,
  },
  {
    category: "House Specials",
    name: "Vietnamese Iced Coffee",
    info: "Espresso sweetened with condensed milk, served over ice",
    price: 5.5,
  },
  {
    category: "House Specials",
    name: "18 to the brain",
    info: "Quad shot sweetened with condensed milk & shaken",
    price: 2,
  },
  {
    category: "House Specials",
    name: "espresso",
    info: "coffee",
    price: 2,
  },
  {
    category: "House Specials",
    name: "espresso",
    info: "coffee",
    price: 2,
  },
  {
    category: "House Specials",
    name: "espresso",
    info: "coffee",
    price: 2,
  },
  {
    category: "House Specials",
    name: "espresso",
    info: "coffee",
    price: 2,
  },
  {
    category: "House Specials",
    name: "espresso",
    info: "coffee",
    price: 2,
  },
  {
    category: "Mocha",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Special Lattes",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Tea Lattes",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Matcha",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "House Iced Tea",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Loose Leaf Tea",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Lemonade",
    name: "tea",
    info: "tea",
    price: 2,
  },
];

export default drinks;
