const drinks = [
  {
    category: "Traditional",
    name: "House Coffee",
    info: "",
    price: 2,
  },
  {
    category: "Traditional",
    name: "Espresso",
    info: "",
    price: 4,
  },
  {
    category: "Traditional",
    name: "Americano",
    info: "",
    price: 4,
  },
  {
    category: "Traditional",
    name: "Cappuccino",
    info: "",
    price: 5,
  },
  {
    category: "Traditional",
    name: "Latte",
    info: "",
    price: 5.5,
  },
  {
    category: "Traditional",
    name: "Cold Brew",
    info: "",
    price: 5.5,
  },
  {
    category: "House Specials",
    name: "1987 (Iced)",
    info: "Hazelnut iced coffee sweetened with condensed milk, topped with sea salt cream & ibarra chocolate",
    price: 6,
  },
  {
    category: "House Specials",
    name: "Vietnamese Iced Coffee",
    info: "Espresso sweetened with condensed milk, served over ice",
    price: 5.5,
  },
  {
    category: "House Specials",
    name: "Vietnamese Hazelnut",
    info: "Espresso sweetened with a salted hazelnut condensed milk, served over ice with a splash of half and halk",
    price: 6,
  },
  {
    category: "House Specials",
    name: "18 to the brain",
    info: "Quad shot sweetened with condensed milk & shaken",
    price: 2,
  },
  {
    category: "House Specials",
    name: "Yuan Yang (YY)",
    info: "Espresso in a blend of black tea sweetened with condensed milk",
    price: 6.2,
  },
  {
    category: "House Specials",
    name: "Drax Thai Tea (Iced)",
    info: "Espresso floated in a Thai Tea",
    price: 6.2,
  },
  {
    category: "House Specials",
    name: "Sea Salt Cream Iced Coffee",
    info: "Sweetened iced coffee & Himalayan Sea Salt Cream",
    price: 5,
  },
  {
    category: "House Specials",
    name: "Caramel Sea Salt Cold Brew",
    info: "Caramel sweetened cold brew topped with sea salt cream",
    price: 6,
  },
  {
    category: "Mocha",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Special Lattes",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Tea Lattes",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Matcha",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "House Iced Tea",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Loose Leaf Tea",
    name: "tea",
    info: "tea",
    price: 2,
  },
  {
    category: "Lemonade",
    name: "tea",
    info: "tea",
    price: 2,
  },
];

export default drinks;
